### ISSUE TITLE
Error in LoginPacket.php [LINE 175] (Undefined Variable 'payloadB64')

### ISSUE THREAD

**Issue by tbhDequan** [LeverylTeam/Leveryl#68]
26.07 23:29:34 [Server] INFO /21:29:34 [CRITICAL] ErrorException: "Undefined variable: payloadB64" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/LoginPacket" at line 175

**Comment by CortexPE** [comment]
Can you please turn on debug mode in pocketmine.yml ?
That'd help a lot...
Send me including the lines that have the [DEBUG] tag.
The lines after the error is what meant.

**Comment by BlazedLucario** [comment]
DEBUG] Packet pocketmine\network\mcpe\protocol\BatchPacket 0xfe78dae55b5d73e24a73de54eef233ce65aace5bfa002f2457062440a0c11a6946d2a452a740620d48c218301f4ae5fd41b9ccafcb65ba35838d36de3db1d79572920b8ab2513333fdccd3fd74cff0ef7ffd9b2f5fbe3c7ef9b7bffefddf7ef9f22fbf258be972fddb3ffcd36ff3b3b398f593e564e9d8ac741ba43bdc0dd7f77aea0f6f86993e0ca3d4f6783ef48df6d48f368fae453a8ce77dbfa4366576cf675408cdb6c7a6d59884944e192d432bd9a67d326446eaf8d66619467435ebb674b72081cfd3d32c4f4f7ea16923230dbd48acfdd299ce199d8abede678c5861c633122d9c204b4ebcc70e01d3339f59265f8bf1a4dfd6bdf5a237d6f251c2f61b2fdc8bb8247763b3f338b5ad666835895b3801ccebd1b5d388049e4e027a606552faa1768ab9b5fce63dfc05d69dcf07b7cbc9cad2dd726890955592defd6e58f0463a7016b46f6b31f8009ecba61139cefa763328ecbda8fce2ece268930beba4c7867d9e86ade5b8eb6c449f3fa5fd5c9be333abf82856c9390e87c63884f514c3bd6b78a67bd6976e79ab8f43bb9804ae31e90d4fa4bc3d92a5d3ae7d07efe87171dac4da3e9fff1fc602d6fc1417b1c4a1679ddc15031cd276f7fe2f3df3e6f4a07be6b4b56bdd1ac9ee382f7e9fa5db6fbd78bdfd6373d39b3332b067c9ea81877fdcdf7e9d0f8a866d4565162fe99df16da42f1fcb63e034ee99f0a75fbf967c3ef9ea1733ba5a386233ee7dfb3a2ec751675db6bef56eb3919e2e9ddee636dbe9c787cc20d1919f7ffbe77ffdbbfff8c72f5ffe1f53a4436de730eb338007d69c91dd3484ed69833f0a7a98b13c1bae1e74b21a9edcd235c98a35814af0f76dc35d792780b69746ce59844dcd0f9bc734a26466d01c6cf0334b84629186a7d73f8bc4263678f5bf5917fd0ceffde33d3cbb1a2f3b6e1cd14d3ae099f03b368c7b76111378262df29560ed00bec784ef19c4a19ef3829f13233fcc96484bebc9f51bda70795c52936f984116727db7607f8275a57a1ca6b967b4b38aea057f8a741ee0f3cce0e714becb0b699614bc4ccef0f97a91cf8ce651f84d6d5a3e9c268155ba4b984b4eb6d3b069c13c173097a5c7ecce1b5e3763338577ed30b16cc0e0f680ff9f2fdb26bc9371b980cfa837d6f0d9ec90c23b5fc70df8cc62ddf6dbeca387ca3ef05bd7f6ef7959e3730bc6b30ef8eef15b786f9bb4db3ae078f83f18cfc3f754f3f09986e7b7f0990ec367ccf47f83fd1b7df2aaff99f47fbaacbe8f4bfcc27e855f07e703efa5c46f27ed619ef899eb57f63d692f86957d10bf869fc2ff3d387e6aff7f90fdbbf6f705bfb158a1ffb9c42fb4aaeff39795ff6d52e1e77895ff015bc4cfcb8e885f97777fcc3fbf5bd9e318888129eda951d9bf07c74fedff0fb27f5f9ceaa4157ec2adfc9f25923f46c5bfaea8fc6f9fa4ff87927f9657f18f9eaff1138f957d2ef1f7e47cba0a7f22f9478aca9edd1fde3bd74fedff0fb27f8b3f66dabe272afed2a757f2577726f9a3d7f25fd1a8f847257f03c95f6249fc8f953d95f9b3a3e2a7716def15c30abf50dabf0bc7cfecff0fb27f5f9caae3d793feb7cef2fb68719d3f63e9ff50f237365fc1bf974afe4ea4bd2bf18767aee2b790fc7d178e9fd9ff1f64ff56fcdc6bff0f42c99f47e97fbdc2cfd38e35fd23f9974afe452a7e8615fffa5cda2bfe9ebcca3e1abea25f59f9763d76797d66ff7f90fd1b7dc2a5ff2ffc51fa914bff6bf77f5a3fa8fc3750f80da4bd63c8fc29eda9ff8a3df7deadc73eb5ff3fc8bef25bbd7e08257fbcc36bf94ff2cf5948fdc2a5ff01bf99d13a81c6d448b08039ec1a8925bcb1017fabfa91e5b715fe61ad7e60afd52f0eeb55fab790fa5793fa55eaa7fe6cf9f6fab3f2cd27f5ff47d9ffd7f53b527f86c9357efd58ea174dfaaf29f18be243626fba506318739e32f0ff985a36f89ffb0c7c4c4ab1e7f9ed36e9ef8e69ad7ed85ce74fb0afc68f65fe2486f4bfe49f2ff157f5a3d594e3efa57d5fc6dfa9ac5f26d2de56f5ab8affcbd6e133fbff03eb7f85df50ea0f2ef1f3a57e54fad309aeeb37d4ffa9fda0331ff113881f70d296f90feaedd4208e57f93f05bddf7e0c07ee765cd29dab776af8a9f8d993fc17d23e184afd2aebcfae2bf5b45fc33f97fc53f80ba57f65fd923564ff48d69f950f3eb1ff3fb0fe57f12753f94bf1cf97f14fe9595de6bfbcca5f5d1847071f52f49fc46fd1e43c3ea4269978e07faa3926e4bf9167b405da87a81735e744f35afea435fc3226f78f59ed1f5be1e74afc54fc65523f899a7e22f175ff8f49fb9eaaa76e248e9fd5ff1f58ff67327ef15afc720a153fa5febcf84fc62fc1babbd32c47ff3be654c3fe596ea1fe6416a7c0df2ee44d0becd7bee6287bef90e89b6350abfff94de5ff42e63fceabf1bb89e4ff54e2d779b6af6a57ff1a3fab5ebf9caffb3f8063357f5154ebfeacfeffc0fa3f90f1d356eb7f92feb325ff4259bf31d53f93fa03ea3fd3d279a6bdf0cfb24d78a6c722a2f4a7b257fe87f14c4fdf3099bfbeebbf49fd6bcbf95cf2af2de327f764feace9d7d4bd8ebf81c4bfa7fa47835affce501ae793faff23eb7fa5ff8fb5fe89aa475c19bffa4a7f48fe84bb03e959261bc4db59b8b7317f0a2d87fd9f349846c07fa22b74c85f9a7d801ca7079a43c57267cc74d5bffbeefc42ed1f5ad39f3df77afcbafe0cebf52bafc57f95bf55fc97ebfdb4feffc8faffa6a61f9612bfd0aff54fa47e608defcf1ff6337d638fcbf42ed6bdc3c8ccf72e7cff4ccf1b507f18543bf9e3f37e3dcd54fd501c7f727ed194fc35e357fa37ae8c9fb9c49fabfc4d65fc8f6afb6f2ded5d19bfc74ae37c52ffff4fd5ff3f3aff6b1de7fd7d07f0e31cc61b959d3ec3fcd75f50cf7f7fff53c65f692fe3f795fead7474153f3b549d3fbec46f21f3778e71a46d86b27f3fa83492e6acb1c797ea39ac2306fd05ebe8b6bb42bbe4cf77cff5a57e8d9c98813fb9c59d69b7b51526affc9d30cac6661e87785e66760697f9ffd98b586d4bfcbcdfe1308d3fbcb37ffac29f72b1aef4a7610f04ec97c45870d4b821cf2ffe7ff7eb6df8a9fc5ba4157e1c75d80b7ee64ff013f0ccfbcfbfaad74bff215cd987f492bfcfed038f52e0527b9cd8ec408a3442be91b5a0c1fbcfbf7fe9f57afcd30ea392f711bfd472103f9367b0ff97fb071aa9fee9fbc77c1b7e8abfb1f60aff0c52c38f41ae047b2ef553faacbfdffb7ae91fb5ce419eba72ff41fc2a453f80b94decfc0ec6dfce1959c3fc9ba19d777e91ffeff6e98fee5fa4c56285f8093d85f8b1d36801f8196d3fb8f8ffdd63be0d3fc5dfe18ff0f325ffba2ffc53f829fefe8a7f5efa5f7919f637d658f78e0cb4fdc84875e41f84263cefdc26ab0ed6b1cd840befd7f8ffc3dc37498c93ec7fb19d8c9f03a9ff65fdf653ff5dce1f643f08e65de98f7ebc8d8ddc0ebb6de1f2bc1c97ce846b276f64900de5f7327fc1fafd5afc74a8c7860712e50e2bde707fe7bc5f4efbfbf8620ff5abc45fabf0ef56f32ff968accbf9d3c1f0bf73ff674bfbe4a6deffcfa5bda6ead7ee75ffc266dfeb37caaafdd3c1fc06f68ef41f8767a57e0ea4bd27aecfdfd9c3fbf77f40885764907f373b5fde9fe9cafe29cced829fbde8cffb52ffcde4faa7d2ffcef0527f4ca20e53e74ff6f4bbfe35ec558dd5cfafd07f2afeed3ba87fe756de058db94dc3e3119e39cc4a7bf427f8eda6ab0ed4b8f786abeeffa8f8ff1d7f31fe779e68e61de603eb14767f8e1ff67f138891c98a6fd4fd03899faa9fa772fcbb5afee6b27ee583e7fe518fe167cff15be92fa3ea4d56f84b7bb27cedfeca2fe4bfad5b344eb07f9a49c01735fd2ef977d93f7e7ae95f96b727b9ff8153b27f70a9dfbc17fc16874a276b7bdbaff56fe8e325ffcd331d7c24f117cb67fd14257a0c767ae962ff7dddc982734b9fb1d467ddfd7966f39b6bfc94ff90bf4eaae9ee75fcb8ca5f06c973962e77facc38c11c1fcca0f00e446baf38c411112567987f19ae175e6dfd2bf74098d688fd57e6affccfa4fffb72ff3a807f72f43207c6cf2bfcdce24430feb896d395f809f67cfe520e4f7e145ff73fdfaf29643f670d736cceede43036a849813f634384caff0ed427a6cbb88cbf796dffabfea7d3bdf45f208e6d18c48fb1e1f029e038d2f48e58b61a33dd3e4bfcdce7fc37677643cdbff7c29ff4e0f29f9f3f4dc20c74b1cc9ff5f82f8cebfe3b57e7272a7ec9f8c164ff9feab2ffa3fab75b699fcafa59c58f58aebfaff4cbf2fafc8549ff5fee3f342afb9016a0df798ae7af8a7fa956e1473d6ec7cff899f91aebc449bf4d93e5afdeffab3871041c75c1b871e19f5b2e4653f07b1c91e8457fdd37534df6aff9f95abf3aeafc213520d63db2fc16f9877bd4f4836aaf36539bb8b80fc230bbee9f75157e412d7e81ff67a577f297aff7ef26113b84c0517fe0ecd4f9a3bc7fc085719dbf15feb63a7f93fd277f77ad9f0692ff43e97f26efef7d777e3250eb57f94bdebff4618ee332bb9cbf6dc17f06e7eafec93a3e606ea42ffcbb93f8f13565c8117d04f907d6418300f44f18eebba87fa616f985fb7f9d0a3f9cd37c003e629bf2a25fc4726fcec29d393eef9a2c036e9664e40fe20331d39e8a1faa7f0ebc2bd3278c1fa4b08e18474941c0be65702305fcdac7d48467342753feeb29ff0f957e50e7ff72ff4f5feaaf087225ec5b579f83df263c3142d8bffedad9d5f7afe25f991c1437afce1f1dc97f4deadf58e927757eadf20797fc5b0faff59bffbc7fcf3b9dd8b5fedf25fec9fb479c801f1e4a4ff67f618fb7e51dc1d5857fbc43017fa84326784717f887f777cb69ceb15f737661fdd7fae13d2f3ac84bf4ffbcd7a9ea079a6f903fc62caf62ed1dcd4187eaf019ecd191b1e8bac0c34994daeafe4571c14fd937d380a0fd769651c0a8b3c5fa03b86955fd263dbde80f75ffe6a8ee4f49ff31e97f2ebee79fd53ef365eb20d6c9b9ce7fc59f4cea3fbf16ff88ea9f7bd7faa1a7ee4f46b5fcd97fb8d66faafe036c147eb07f19f2cfedeb26ade967883f6572c2f3f3b141b602304a337b0cf60cf083f8cb69c53f93af3cccf10387621c4d06690362c4d1cf6c8c5f4f787f65ce99f62bfd2f92091bfcbf9dda0e9e630cd91aeabf52ac66b07f2ff8715b60bf6fcb8d36e8b0fd9e65a063147e6ecfd982bd218c26d8eff74108f6a680dc50f59f16387fca1dac9f0cec11a8f307efeafe5b775acb5f2ff891951343fd726011dda9fcabee6f2d6afa45dd9f1caafc27f583a1ce8fa57eea28fd6c5dc74f9fdf5edfbf54f75794fe0c87b8ff4c9cbf6f3b885fc98b3df2e8242c5cffbdc673a8f17bb9891c23191f428cbe7135ac3fb889f1f7821fd769755f76c22bfe19b1a61723bd7387fd13e026c1fd1f649b5fe97f4d588ef5fbfe48fb58bfe76bf43fd40f8fc89f919153c8914ddfd23bd8e326889fb66138bec2af21ac05f24f17d18281b6097de45f99ef70fe81ee50883f5b2fcbd13e0c32bb76fecf247ffcdafd55c4af8098863dca35dd29fd25fdcf17c6f5f9953abf54f51795f98fd7fa07aa7ebae0ff50fbfd81e29f48afefbf07c973fe9be91cf963d00cfc5f2e321ff1333b4d51f5abf72bf89e6ddac7f5b703aedb98ff75ec578f4cdbc7fe0d686aecdf3c7a1ada0b017ace1be9ce1df6bb47c6e9e09d157eddf6913ff7af7e94ff6ecd11e46088118774851c8fe16fd83ff8f7b2a505fd8a7f510c1a7fc29daaff1767ba09f957e2578a4380f8011771fea4e7207f0f7e76c2f1974104f9cf5cf8157ee6e28916b1b26fafbda083fb774d71fd86336075fd1149fd113fdfdf9ab0a40c07f116f66808faffc647df94f786d080a3ba0dbc7c80fd234850bbffaace5f72ef95feafb3afd59f2affa5b5fa4148fe07527fa9fa07fbff279ae7b8fe6d80fd7f5d58387f92a5b87f417fef7bd8ff16e8ff92dc08dcff4cf8e83fb78ff8b71b9ca3fd7d7356dd115bf8d57945e970bc23483307f4fbee58f5bf4a5048d6f0a7f53fedbe8adf16ff86f11f12189f583a9edf1f8446707c9d1569e5ff04cf4b4a3162f0991be536eccd66100ac4efc9c3f312d3e9ce10db086a5d7ebb75998c3fac2030ff4c8b01ff9141baa8835c6381faa9c938e982ff5715b65a4ad17e3e4809dedf118c22fe8e9771585b1e4c35524cfac26610e3fc70e150d8bfbe91e3fd9d1db5abfb5beb10ea9779b0f03da85fe7165f436c8b3ccd262ff90ff2c5e5f703805fc0e0ef5e4ea909b94db71f62d016736e13af8841cb2d708f81ecc81d5c7fcaaafcb1c4fe07f8bfcaff89b9e98046f543ec1f1b4db3ca1fe5c245fca6798efc6d4c4d82fe03cc6d6364521bf5f3a4e710fe6cbf177480e74dfb0eea874944a67f76fef12a7ec04ffc7b12a60b1c9f813fb17f8bbd4698f74a9e3fa5b2ff3d5808cc7fae8df8ed8c6aff98bc81e72fc420c85fd03402f54b39b5abf8c139c68f32efe3fe9bdbce1aed034e31fe0b1aa5903f527302fb6fdedf4fb0ff13328af177087917eacf85c9f02c4d6b3e09c8716edfb67dd8bfd3b0ba234b66450afa33ef52f0cd9c718c5f803fc7fef7d0cbb0fe447bfba5fe30608ff990b720fec1fe31a856dd0da2b2ffcbbbe83f017ae465fc9cc7a8df0c3ec0f9cf329b7a905b122dc7fcd3a0957e489b957e30da3bf86c9b58e91a73cb9421ff72dbc7310cea30c476bd20957ed0307fb527b43a2f6c3730fe12fcfd2af287a517fdf4aed79dfffcbb4747e06f3673a2c561338b23278b34a227263dccaa67683e2beca7d4aa7e3fbac4df5672967b49d12ea6e1097f037ac4df9f7e5bfcfe7413dcb69c43a335cabdb633eaff71cf9cf8ae75279e1637c1d1fa6afb9d87939eda816824937d2bd8764baba5cfc2c94c58dd514eee56d3f970e7ec6363678fb569ebf77973b8f8e3ae3d38163d3db8dd3ca5ac31b97583f33cdb587fb44ebbe3fd4aa336a4e57011fd27ca530274
2017-07-27 05:16:00 [CRITICAL] ErrorException: "Undefined variable: payloadB64" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/LoginPacket" at line 175
2017-07-27 05:16:00 [DEBUG] #0 /src/pocketmine/network/mcpe/protocol/LoginPacket(175): pocketmine\{closure}(integer 8, string Undefined variable: payloadB64, string /root/lev/src/pocketmine/network/mcpe/protocol/LoginPacket.php, integer 175, array Array())
2017-07-27 05:16:00 [DEBUG] #1 /src/pocketmine/network/mcpe/protocol/LoginPacket(84): pocketmine\network\mcpe\protocol\LoginPacket->decodeToken(string eyJhbGciOiJFUzM4NCIsIng1dSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFL3E4OWRRaURzWEcrdGNIU2dJSEpiWXRjbC81MmNTSVdxbldxSm00K2dWQXZnSzJaeURaZG1GUUNEWkVkNXhJTkcxVDUvTU1kSUE3VnZLOG91QnhDL0lKcUtpQWtZYzNPL3BqaFE5WE5NMmJTSURqMFdXNTQ1NTRvUzczSW0xYVEifQo.eyJleHAiOjE1MzI2NjEzNDgsImV4dHJhRGF0YSI6eyJkaXNwbGF5TmFtZSI6IkJsYXplZEx1Y2FyaW8iLCJpZGVudGl0eSI6IjYwZjcyYWI2LWVkNmItM2Q3My1iMzA1LWFmOTM2ODIxNzAwNiJ9LCJpZGVudGl0eVB1YmxpY0tleSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFL3E4OWRRaURzWEcrdGNIU2dJSEpiWXRjbC81MmNTSVdxbldxSm00K2dWQXZnSzJaeURaZG1GUUNEWkVkNXhJTkcxVDUvTU1kSUE3VnZLOG91QnhDL0lKcUtpQWtZYzNPL3BqaFE5WE5NMmJTSURqMFdXNTQ1NTRvUzczSW0xYVEiLCJuYmYiOjE1MDExMjUzNDd9Cg.D36xo1Q3a8s8A2cswem-bdrfDYnr_p6DeUNHFbcjoVW_gA7eHm4FEXzkYiRP2fK1iqzwTJ4gUZSa77zVeO7SmbRjhJZpLDf7LzLXBnz8fDAkK1diJDpAks1wok2NXwVy, string MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE8ELkixyLcwlZryUQcu1TvPOmI2B7vX83ndnWRUaXm74wFfa5f/lwQNTfrLVHa2PmenpGI6JhIMUJaWZrjmMj90NoKNFSNBuKdm8rYiXsfaz3K36x/1U26HpG0ZxK/V1V)
2017-07-27 05:16:00 [DEBUG] #2 /src/pocketmine/Player(3947): pocketmine\network\mcpe\protocol\LoginPacket->decode()
2017-07-27 05:16:00 [DEBUG] #3 /src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\LoginPacket object)
2017-07-27 05:16:00 [DEBUG] #4 /src/pocketmine/Player(3954): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\Player object)
2017-07-27 05:16:00 [DEBUG] #5 /src/pocketmine/network/mcpe/RakLibInterface(148): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2017-07-27 05:16:00 [DEBUG] #6 /src/raklib/server/ServerHandler(103): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 71.48.135.169:58918, raklib\protocol\EncapsulatedPacket object, integer 0)
2017-07-27 05:16:00 [DEBUG] #7 /src/pocketmine/network/mcpe/RakLibInterface(83): raklib\server\ServerHandler->handlePacket()
2017-07-27 05:16:00 [DEBUG] #8 /src/pocketmine/network/Network(185): pocketmine\network\mcpe\RakLibInterface->process()
2017-07-27 05:16:00 [DEBUG] #9 /src/pocketmine/Server(2674): pocketmine\network\Network->processInterfaces()
2017-07-27 05:16:00 [DEBUG] #10 /src/pocketmine/Server(2434): pocketmine\Server->tick()
2017-07-27 05:16:00 [DEBUG] #11 /src/pocketmine/Server(2310): pocketmine\Server->tickProcessor()
2017-07-27 05:16:00 [DEBUG] #12 /src/pocketmine/Server(1846): pocketmine\Server->start()
2017-07-27 05:16:00 [DEBUG] #13 /src/pocketmine/PocketMine(510): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/lev/, string /root/lev/, string /root/lev/plugins/)
2017-07-27 05:16:00 [NOTICE] Blocked 71.48.135.169 for 5 seconds
2017-07-27 05:16:10 [INFO] [/71.48.135.169:58918] logged out due to Login timeout




there ya go! please fix when ya can
